### ISSUE TITLE
Maximum number of cells?

### ISSUE THREAD

**Issue by wikiselev** [davismcc/archive-scater#114]
What is the maximum number of cells supported by `newSCESet`? I've tried 10^5 cells and got this error:
```
Error in .checkedCall(cxx_missing_exprs, exprs(object)) : 
  long vectors not supported yet: ../../../../R-devel/src/main/memory.c:3424
```
I then tried 99,999 cells and got the same error.

**Comment by wikiselev** [comment]
Forgot to say that it worked ok with ~89,000 cells.

**Comment by LTLA** [comment]
I daresay it's because I used the length of the matrix (product of number of rows and columns) in one of my C++ functions. Presumably this exceeds the maximum vector size allowed in R, hence the error. I've since wound back the use of C++ functions (see #112) so this should no longer be a problem in the next release.

**Comment by wikiselev** [comment]
Thanks, Aaron! So, it's not in bioc-devel yet?

**Comment by LTLA** [comment]
No, it's not even in the Github master branch yet. Nudge @davismcc.

**Comment by davismcc** [comment]
This issue was moved to davismcc/scater#15
