### ISSUE TITLE
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘plotPCA’ for signature ‘"SCESet"’

### ISSUE THREAD

**Issue by cguzzo** [davismcc/archive-scater#133]
Hi there,

I'm getting the following error when I try to plot the PCA of the SCEObject:

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘plotPCA’ for signature ‘"SCESet"’

I've double checked and scater is properly loaded in my sessionInfo() - I'm on R-3.4.1. The same command was still working a few days ago?

Many thanks!

**Comment by LTLA** [comment]
I guess you're using the very newest version of _scater_. We recently migrated to the `SingleCellExperiment` class, which uses the `SummarizedExperiment` class instead of the `ExpressionSet` class. This provides a more modern interface that supports more data formats and is under active development. Try running `updateSCESet` or `toSingleCellExperiment` on your `SCESet` object, which will convert this to a `SingleCellExperiment` object for you. This can be used in `plotPCA` as before.

**Comment by cguzzo** [comment]
Thanks Aaron, updateSCESet worked perfectly

**Comment by cguzzo** [comment]
I'm having another issue when creating a new SCEobject. The function "newSCESet" is deprecated and I can't find another way to create a single cell experiment object from an expression matrix - is there a new way of doing this?
