### ISSUE TITLE
Add wrapper for Salmon

### ISSUE THREAD

**Issue by davismcc** [davismcc/archive-scater#20]
After reading the Salmon bioRxiv pre-print I am sufficiently impressed. It would be very nice to add Salmon as an alternative to kallisto to that the package remains relatively agnostic to quantification methods.

**Comment by rob-p** [comment]
Hi @davismcc — I'm the lead developer of salmon.  Please let me know if there's any way that I can help with this!

**Comment by kieranrcampbell** [comment]
This is actually implemented in `readSalmonResults(...)` which works well, so not entirely sure why it's still open.

**Comment by davismcc** [comment]
Hi @rob-p (and Kieran),

Thanks for getting in touch - pleased to see that you're aware of our little project here. As Kieran mentions, I have implemented the `readSalmonResults` function to do what the name suggests - so we're half-way there with what I had planned. 

The reason this issue is still open is that I'd like to have a `runSalmon` wrapper function to match the `runKallisto` function that implemented a while back. 

@rob-p - the _ideal_ way you could help with this would be to submit a pull request that adds a `runSalmon` function that uses the template of `runKallisto` to the `salmon-wrapper.R` file in the source. That would likely be the fastest way to get this incorporated in the pkg (if I just have to review the PR, test and incorporate then that's awesome).

If you don't have the familiarity with R and/or the bandwidth to implement `runSalmon`, then getting your advice on setting sensible defaults for Salmon to apply in a `runSalmon` function and perhaps some contribution on the docs for the function (explaining options and methods for Salmon better than I would be able) would be helpful.

Again, really appreciate your offer! Let me know what works. It's been lingering here for a while now, so a little push to get `runSalmon` implemented would be very cool.

D.

PS: Congratulations/thanks for your work on Salmon. Great method and piece of software!

**Comment by rob-p** [comment]
Hi @davismcc,

  Thanks for the encouraging words and for the explanation of what is required here.  My `R`-fu is not particularly strong, but I'll take a look at `runSalmon` and see what I can come up with.  If I can put something reasonable together myself, I'll submit a PR.  Otherwise, I'll advise the best way to wrap the call to `salmon`.

Thanks!
Rob

**Comment by davismcc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SdxjM3y5&#x2F;82-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue</a>

**Comment by davismcc** [comment]
Quick update: I have just committed changes to the functions for reading Salmon results, so these should now work with Salmon v0.7.0+ results. 

I'm aiming to write the `runSalmon` function this afternoon.

**Comment by davismcc** [comment]
Hi @rob-p 

It took me a little longer than planned, but I have just committed a `runSalmon` wrapper function to the package. It would be great if you could take a look and see if it captures the most important functionality of `Salmon` in a more or less sensible way. I have consciously not implemented every possible option (since there are quite a lot), but the vast majority can be accessed through the wrapper.

If you would be able to undertake some testing of the function, then that would be fantastic. 😸 

The deadlines for the next Bioconductor release are approaching in the next couple of weeks, so it would be great to have this function working smoothly by then.

Best
Davis

**Comment by rob-p** [comment]
Hi Davis,

  Great!  Thanks for diving into this.  I'll take a look ASAP.

--Rob

**Comment by davismcc** [comment]
Hi Rob

The deadline for new functionality for the next Bioconductor release is the end of tomorrow (Oct 7). Thus, if you have any feedback on this function it would be great to receive it ASAP. Whether you have time to take a look or not, this will be included in the next release.

Best
Davis

**Comment by rob-p** [comment]
Hi Davis,

  I'm moving this to the front of my priority list!  I'll take a look at this after I teach, and get you any feedback before tomorrow.

Best,
Rob

**Comment by davismcc** [comment]
Thanks, Rob!

**Comment by rob-p** [comment]
Hi Davis,

  I've tested out the wrapper a bit; thanks for your work on this!  In addition to being a part of scater, it's awesome to generally have a way to run salmon directly from within R.  I have a few comments on the current function (I may investigate a bit more tonight, but these are the main ones).
- The default `salmon_cmd` name is "Salmon", but the default executable is named "salmon".  This, of course, is a meaningless distinction on OSX.  But on linux, this means users will have to pass an overridden `salmon_cmd`.
- There may be a better way to set the thread usage.  Right now it seems the `n_cores` sets up runs of up to `n_cores` concurrent salmon processes.  However, the default behavior of salmon, if no other options are provided, is to query for the maximum supported number of hardware threads and use all of them.  So, if you have many samples here, the default behavior will be to start `n` salmon processes, each of them attempting to use the maximum number of threads.  There are a few ways to address this.  One would be to change `n_cores` to `n_processes`, so the interpretation remains the same, and then to add a `n_thread` or `n_thread_per_process` option and set it to a small default value (e.g. 4 or so).  The user could change the default number of threads if they want, but this would better fit the model of parallelizing over both samples (via multiple processes) and threads (within a given sample).
- The `advanced_opts` currently seem to be passed through the function, but never applied.  Is this intended?
- The documentation says that the default library type is `A`, [but if I make the call without setting the `lib_type` it looks to actually be `NULL`](https://github.com/davismcc/scater/blob/master/R/salmon-wrapper.R#L361), which generates an invalid command to salmon (i.e. `-l` has no argument).
- This last one is more of a slight interface tweak that would future proof the scater interface between now and the next bioconductor release.  Salmon 0.7.x currently has a command-line option (though it's "hidden") to turn on positional bias modeling.  This is called `--posBias`.  In salmon 0.7.3, which should hit soon, this will be exposed (though probably still turned off by default).  I'd recommend adding an option called `posBias`, with a default value of `FALSE`, so that users can easily get at this option in the current and upcoming releases (when it will no longer be hidden).

Again, thanks for all your work on this.  I'll let you know if I see anything else worth commenting on before tomorrow morning.

--Rob

**Comment by davismcc** [comment]
Hi Rob

Thanks for working over the code. Great to get your eyes on it and have you test it. In response to your points above, respectively:
- `salmon_cmd`: simple typo, sadly - fixed in latest commit
- threads/processes: thanks for the explanation and suggestion. What you suggest makes total sense, so I've changed the `n_cores` argument to `n_processes` and added the argument `n_threads_per_process`. So now the user can control parallelization across and within samples like you suggest.
- `advanced_opts`: it was not intended to ignore these! Thanks for catching this. Fixed in latest commit. 
- `lib_type`: thanks for catching this - I have simply changed the default value of the argument to `"A"` to give the intended behaviour. I think I changed my plans for how to implement applying that argument halfway through writing the function. Fixed now.
- `posBias`: thanks for letting me know about this (and nice feature to look forward to). I've done exactly as you've suggested. Easy.

Let me know if you have any more suggestions to incorporate into the imminent release.

Best
Davis

**Comment by davismcc** [comment]
Having not heard more and it being the end of the day here I'm going to close this and submit the updated package to Bioc devel. I think all the major features are there, so if we discover any other bugs/issues, please just raise as a new issue. Looking pretty good to me now though.
