### ISSUE TITLE
calculateTPM() produces zero matrix

### ISSUE THREAD

**Issue by wikiselev** [davismcc/archive-scater#32]
Hi Davis,

I have just tried both calculateTPM() and calculateFPKM() with the same effective_length argument and got some meaningful output for FPKM, but completely 0 expression for TPM. No errors or warnings were produced during the function calls. Is there any rounding in the TPM function?

Cheers,
Vlad

**Comment by lazappi** [comment]
I have had the same problem. 

I think it may be caused by the line `denom <- log(colSums(exp(rate)))` in `.countToTpm` which can cause denom to become all NA.

Perhaps it should be `denom <- log(colSums(exp(rate), na.rm = TRUE))`?

P.S. It works if you calculate FPKM first then use `calculateTPM(data, calc_from = "fpkm")`.

**Comment by davismcc** [comment]
Thanks, both, for the bug report and suggested fix. I have fixed this in the latest commit (`ad203e16624fb07b0eca50fa9acae4001996747b`). Please let me know if it does not perform as expected!
