### ISSUE TITLE
QC metrics error

### ISSUE THREAD

**Issue by wikiselev** [davismcc/archive-scater#71]
Hi Davis,

I am trying to create a scater object from this dataset (kolodziejczyk.rds):
https://www.dropbox.com/s/2245itc3zv3m9lg/kolodziejczyk.rds?dl=0

The values in the dataset are CPMs. So I run this:
```
kolodziejczyk <- readRDS("kolodziejczyk.rds")
cell_info <- data.frame(cell_id = colnames(kolodziejczyk))
cell_inds <- paste("Cell", 1:ncol(kolodziejczyk), sep = "_")
rownames(cell_info) <- cell_inds
cell_exprs <- kolodziejczyk
colnames(cell_exprs) <- cell_inds
pd <- new("AnnotatedDataFrame", data = cell_info)
sceset <- newSCESet(cpmData = cell_exprs, phenoData = pd)
is_exprs(sceset) <- exprs(sceset) > 0
```

There were no errors so far. But when I try to compute the QC metrics:
```
sceset <- calculateQCMetrics(sceset)
```
I get this error:
> Error in data.frame(value, row.names = rn, check.names = FALSE, check.rows = FALSE) : 
>   row names supplied are of the wrong length

Looks like I have the latest version of scater from Bioc-devel. Do you know what the problem can be?

Cheers,
Vlad

My sessionInfo():
```
R Under development (unstable) (2016-10-20 r71540)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] scater_1.2.0        ggplot2_2.1.0       Biobase_2.34.0     
[4] BiocGenerics_0.20.0
```

**Comment by LTLA** [comment]
Seems like it happens because `calculateQCMetrics` doesn't actually calculate QC metrics for the CPMs. As no other values (counts, FPKMs, TPMs, etc.) are present, this means that an internal variable `cols_to_log` becomes empty, leading to the error being thrown above. This is a bug, so the simplest solution (on our end) would be to add a code chunk to calculate QC metrics for CPMs. The long-term solution would be to refactor this into a set of loops, because from what I can see, a lot of the code is just duplicated.

**Comment by davismcc** [comment]
Changes from Aaron resolved the error caused here a while back.

However, I have taken this opportunity to remove nonsensical QC metrics (e.g. pct exprs metrics make no sense when exprs values are on the log scale and can be negative). Latest commit removes a lot of these extraneous metrics from the output SCESet from calculateQCMetrics(). 

It's possible that these changes could break some people's code, but this is the responsible thing to do in the long run so that we're not outputting nonsense.
