### ISSUE TITLE
Excess QC metrics

### ISSUE THREAD

**Issue by wikiselev** [davismcc/archive-scater#73]
At the moment there are four similar types of QC metrics corresponding to:
_top_50_
_top_100_
_top_200_
_top_500_

I think they mostly repeat each other. Would you consider keeping only one of them and removing all others?

**Comment by davismcc** [comment]
I quite like having access to all four, so unless you can persuade me that it's causing problems I'm inclined to keep this as it is.

**Comment by wikiselev** [comment]
No, I don't want to persuade you 👍

**Comment by LTLA** [comment]
I'm going to resurrect this issue, because some of the QC metrics aren't particularly useful now that `exprs` is defined as being log-transformed. This includes almost all the metrics derived from `exprs`; for example, what is the meaning the the sum of log-transformed values? It's not even the geometric mean. If `calculateQCMetrics` reports that the top 50 features take up X% of this sum, how should I interpret this? In fact, the only metrics that _do_ make sense are `mean_exprs` and `exprs_rank`.

I would also suggest changing `n_cells_exprs` to `nexprs_cells`, lest users think that the number of expressing cells is calculated from `exprs`. Which it can be, but not always, depending on whether expression values higher up the hierarchy are available to use.
