### ISSUE TITLE
NormaliseExprs with non-logged values

### ISSUE THREAD

**Issue by jenzopr** [davismcc/archive-scater#99]
Dear Aaron and Davis,

just a quick question: Suppose I used the sum factor normalisation but then still have a batch effect in the PCA coming clearly from a technical variable (like C1-Machine or so). As indicated in the Scater Case Study from the paper, we can regress out this variable. 
Now does it make sense to use the sum factor normalized values, but not on log scale? I suppose no, because limma is used inside normaliseExprs and limma requires logged values?
Additionally, after regression, does it make sense to standardize residuals?

Best and thanks!
Jens

**Comment by LTLA** [comment]
The log-transformation provides a measure of variance stabilisation with respect to the mean. This improves the precision of the linear model fit, where the use of normality means that all observations are assumed to have equal variances conditional on the mean. Without variance stabilisation, large counts would have larger absolute variances (ignoring the effects of normalisation for simplicity); any fluctuations in those observations would have undue influence on the model fit, such that information from smaller counts is effectively ignored. On a more practical note, the log-transformation means that negative values still make sense in terms of log-expression; without any transformation, you would end up with negative "counts", and who knows what that actually means?

After regression, I assume you're planning to scale the observations to equalise the variance of each gene before PCA. This is fairly standard and I don't see a problem with doing so, _provided you have selected highly variable genes beforehand_. Otherwise, your PCA may be driven by small technical effects across a majority of genes that do not exhibit interesting biological heterogeneity. This is particularly true after standardisation, where these small effects will get amplified to the same variance as interesting genes. Selection is similarly important for other forms of dimensionality reduction, e.g. _t_-SNE, as well as clustering. (I usually do not standardise in these cases, in order to maintain sensitivity if only a few HVGs are driving the separation between cells.)

**P.S.** For general questions like this, it is better to ask on the [Bioconductor support site](https://support.bioconductor.org).

**Comment by jenzopr** [comment]
Thanks a lot, Aaron! Your response helped a lot.
Best,
Jens
